### ISSUE TITLE
specifying folder when creating article

### ISSUE THREAD

**Issue by lgwapnitsky** [dandesousa/Lapis#46]
I sort my posts by category folder. I'd love to be able to specify a category and use that variable as the initial folder instead of the default "posts". Is that possible?

Thanks

**Comment by dandesousa** [comment]
I could make a category variable that is usable in the article path. Right now you can look at the docs for configuration yml file thats created. By default its posts with some date vars. 

I can take a look tonight and see if its as simple as just adding that category keyword or if well need to move around when the path is determined.

**Comment by lgwapnitsky** [comment]
Great. Looking forward to it!

**Comment by dandesousa** [comment]
I did get a chance to look at the code briefly. I can easily setup the app so you could do this:

1.) Change article path in your .lapis.yml to article_path: posts/{category}/{year}/{month} or {category}/{year}/{month}
2.) Create your articles using

```
lapis create article "My Article Title" -c categoryname
```

Right now I don't support category as a var but its trivial to add. What do you think of this solution? 

What I have in mind wouldn't change the location if you edit the markdown file to change the category, only if you specify the category when creating it.

**Comment by lgwapnitsky** [comment]
That's exactly what I'm looking at!

**Comment by dandesousa** [comment]
I've updated this in master, could you be a beta tester :-)? You can install lapis from master with:

pip install -e git+https://github.com/dandesousa/lapis.git#egg=lapis

If you confirm I'll close this Issue and make a release.

**Comment by lgwapnitsky** [comment]
how do i set the variable in the e config file?

thank you

**Comment by dandesousa** [comment]
If you created it with the newconfig command there should be a .lapis.yml file in your home directory

—
Daniel DeSousa

**Comment by lgwapnitsky** [comment]
right, but what variable do I use for the "category"?

THank you

**Comment by dandesousa** [comment]
Oh sorry  {category}

Daniel DeSousa

On Sat, May 9, 2015 at 9:48 AM, Larry G. Wapnitsky <notifications@github.com

> wrote:
> 
> right, but what variable do I use for the "category"?
> 
> THank you
> 
> On Sat, May 9, 2015 at 8:54 AM, Daniel DeSousa notifications@github.com
> wrote:
> 
> > If you created it with the newconfig command there should be a .lapis.yml
> > file in your home directory
> > 
> > —
> > Daniel DeSousa
> > 
> > On Sat, May 9, 2015 at 8:52 AM, Larry G. Wapnitsky

**Comment by lgwapnitsky** [comment]
Not working:

 % lapis create article test -c news
                                            (env: pelican_py3)
Traceback (most recent call last):
  File "/home/larry/pyvenvs/pelican_py3/bin/lapis", line 9, in <module>
    load_entry_point('lapis==0.2.1b0.dev0', 'console_scripts', 'lapis')()
  File "/home/larry/pyvenvs/pelican_py3/src/lapis/lapis/command.py", line
354, in main
    args.config = Config(args.pelican_config, conf=args.lapis_config)
  File "/home/larry/pyvenvs/pelican_py3/src/lapis/lapis/config.py", line
25, in **init**
    self.**parse_conf_data(conf_filename)
  File "/home/larry/pyvenvs/pelican_py3/src/lapis/lapis/config.py", line
37, in __parse_conf_data
    data = yaml.load(f)
  File
"/home/larry/pyvenvs/pelican_py3/lib/python3.4/site-packages/yaml/__init**.py",
line 72, in load
    return loader.get_single_data()
  File
"/home/larry/pyvenvs/pelican_py3/lib/python3.4/site-packages/yaml/constructor.py",
line 35, in get_single_data
    node = self.get_single_node()
  File
"/home/larry/pyvenvs/pelican_py3/lib/python3.4/site-packages/yaml/composer.py",
line 36, in get_single_node
    document = self.compose_document()
  File
"/home/larry/pyvenvs/pelican_py3/lib/python3.4/site-packages/yaml/composer.py",
line 55, in compose_document
    node = self.compose_node(None, None)
  File
"/home/larry/pyvenvs/pelican_py3/lib/python3.4/site-packages/yaml/composer.py",
line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File
"/home/larry/pyvenvs/pelican_py3/lib/python3.4/site-packages/yaml/composer.py",
line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File
"/home/larry/pyvenvs/pelican_py3/lib/python3.4/site-packages/yaml/parser.py",
line 98, in check_event
    self.current_event = self.state()
  File
"/home/larry/pyvenvs/pelican_py3/lib/python3.4/site-packages/yaml/parser.py",
line 439, in parse_block_mapping_key
    "expected <block end>, but found %r" % token.id, token.start_mark)
yaml.parser.ParserError: while parsing a block mapping
  in "/home/larry/.lapis.yml", line 3, column 1
expected <block end>, but found '<block mapping start>'
  in "/home/larry/.lapis.yml", line 12, column 2

My config:

---

# terminal color options

termcolors:
    # enables terminal colors (default: no)
    enabled: yes

# selects the editor (default: vim)

editor: vim

# selects default markup language (default: markdown)

# uncomment desired default markup below

markup: markdown

# markup: restructuredtext

# preferred articles stub

article_path: {category}/{year}/{month}

**Comment by dandesousa** [comment]
as a workaround you should quote your article_path. The yaml parser doesn't like it when the object starts with { as it appears it expects to to be the start of a block / dictionary.

If you do "{category}/{year}/{month}/blah/blah" (quote your article_path value) it should work. If you had posts/{category}/... it would have also worked cause it inferred it.

**Comment by lgwapnitsky** [comment]
perfect!

**Comment by dandesousa** [comment]
You should update to the latest from pip i already made the release. Should be 0.2.1b
